"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var b2cRegistrationB2CPortalPO_1 = require("../PO/b2cRegistrationB2CPortalPO");
var RandomStringGeneratorUtil_1 = require("../Util/RandomStringGeneratorUtil");
var protractor_1 = require("protractor");
var waitStatementUtil_1 = require("../Util/waitStatementUtil");
var selectUtil_1 = require("../Util/selectUtil");
var b2cRegistrationB2CPortalLib = /** @class */ (function () {
    function b2cRegistrationB2CPortalLib() {
    }
    b2cRegistrationB2CPortalLib.prototype.selectB2CRegistrationTabB2CPortal = function () {
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bRegistrationTab.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
    };
    b2cRegistrationB2CPortalLib.prototype.selectAddCandidateB2CregistrationB2CPortal = function () {
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bRegisAddCandBttn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
    };
    b2cRegistrationB2CPortalLib.prototype.b2cRegistrationB2CPortalusingAddCandidate = function () {
        var firstname = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(5);
        var lastname = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(5);
        var passportNum = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(5);
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bFirstName.click();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bFirstName.sendKeys(firstname);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bLastName.sendKeys(lastname);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bDOBday.sendKeys("11");
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bDOBMonthDrpdwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bDOBMonthDrpdwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bDOBMonthDrpdwn.selectByIndex(4);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bDOBYear.sendKeys("1991");
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bGenderMale.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bIDdrpdwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bIDdrpdwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bIDdrpdwn.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bidDocNum.sendKeys(passportNum);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bidexpday.sendKeys("11");
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bidexpMonthDrpdwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bidexpMonthDrpdwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bidexpMonthDrpdwn.selectByIndex(5);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bidexpyear.sendKeys("2038");
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bNextBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bqualificationLeveldrpdwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bqualificationLeveldrpdwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bqualificationLeveldrpdwn.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bStabdardRadioBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bSessionStagedrpDwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bSessionStagedrpDwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bSessionStagedrpDwn.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bPrepratncntrdrpdwn = new selectUtil_1.selectUtil(b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bPrepratncntrdrpdwn);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bPrepratncntrdrpdwn.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bexamdrpdwn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bexamselctn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bPickSelectedExam.click();
        protractor_1.browser.sleep(700);
        protractor_1.browser.executeScript('window.scrollTo(0,document.body.scrollHeight)');
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bAddBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait2();
        protractor_1.browser.executeScript('window.scrollTo(0,document.body.scrollHeight)');
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bFirstnameValidation.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2bFirstnameValidation.sendKeys(firstname);
        waitStatementUtil_1.waitStatementUtil.customWait2();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2blastnameValidation.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2cRegistrationB2CPortalPO_1.b2cRegistrationB2CPortalPO.b2blastnameValidation.sendKeys(lastname);
        waitStatementUtil_1.waitStatementUtil.customWait2();
    };
    return b2cRegistrationB2CPortalLib;
}());
exports.b2cRegistrationB2CPortalLib = b2cRegistrationB2CPortalLib;
